from tkinter import *
tk = Tk()
tk.title("Calculator")
height = 3
width =9
borderwidth = -1
canvas1 =Canvas(tk, width = 150, height = 40)
canvas1.pack()
first_frame = Frame(tk)
first_frame.pack(side = 'top')
entry = Entry(tk, font =('Calibri', 18), borderwidth=4) 
canvas1.create_window(76,22, window=entry, width = 285, height=45)

bottom_frame = Frame(tk)
bottom_frame.pack(side='top')
last_frame = Frame(tk)
last_frame.pack(side = 'top')
final_frame = Frame(tk)
final_frame.pack(side = 'top')
final_frame2 = Frame(tk)
final_frame2.pack(side = 'top')
frame = Frame(tk)
frame.pack(side = 'top')

no1= Button(final_frame2, text="1", width= width, background='white', height=height, borderwidth=borderwidth)
no1.pack(side = 'left')
no2= Button(final_frame2, text="2", width= width, background='white',height=height, borderwidth=borderwidth)
no2.pack(side='left')
no3= Button(final_frame2, text='3', width= width, background='white',height=height, borderwidth=borderwidth)
no3.pack(side='left')
no4= Button(final_frame, text="4", width= width, height=height, background='white', borderwidth=borderwidth)
no4.pack(side = 'left')
no5= Button(final_frame, text="5", width= width, background='white', height=height, borderwidth=borderwidth)
no5.pack(side='left')
no6= Button(final_frame, text="6", width= width, background='white',height=height, borderwidth=borderwidth)
no6.pack(side='left')
no7= Button(last_frame, text="7", width= width, background='white',height=height, borderwidth=borderwidth)
no7.pack(side = 'left')
no8= Button(last_frame, text="8", width= width, background='white',height=height, borderwidth=borderwidth)
no8.pack(side='left')
no9= Button(last_frame, text="9", width= width, background='white',height=height, borderwidth=borderwidth)
no9.pack(side='left')
plus= Button(final_frame2, text= '+', width= width, height=height, borderwidth=borderwidth)
plus.pack(side='left')
minus= Button(final_frame, text= '-', width= width, height=height, borderwidth=borderwidth)
minus.pack(side='right')
times= Button(last_frame, text= 'x', width= width, height=height, borderwidth=borderwidth)
times.pack(side='right')
divide= Button(bottom_frame, text= '/', width=width,height=height, borderwidth=borderwidth)
divide.pack(side='right')
clear= Button(bottom_frame, text="Clear", width= (width*3)+3, height=height, borderwidth=borderwidth)
clear.pack(side = 'left')
equal= Button(frame, text= '0', width= int((width*4)/3)+7, background='white',height = height, borderwidth=borderwidth)
equal.pack(side='left')
point= Button(frame, text= '.', width= width, height = height, borderwidth=borderwidth)
point.pack(side='left')
equal= Button(frame, text= '=', width=width, height = height, borderwidth=borderwidth)
equal.pack(side='left')

tk.resizable(False, False) 
tk.mainloop()
