from tkinter import *
tk = Tk()
frame = Frame(tk)
frame.pack(side = 'top')
bottom_frame = Frame(tk)
bottom_frame.pack(side='top')
last_frame = Frame(tk)
last_frame.pack(side = 'top')
final_frame = Frame(tk)
final_frame.pack(side = 'top')
final_frame2 = Frame(tk)
final_frame2.pack(side = 'top')
no1= Button(frame, text="1", width= 8)
no1.pack(side = 'left')
no2= Button(frame, text="2", width= 8)
no2.pack(side='left')
no3= Button(frame, text='3', width= 8)
no3.pack(side='right')
no4= Button(bottom_frame, text="4", width= 8)
no4.pack(side = 'left')
no5= Button(bottom_frame, text="5", width= 8)
no5.pack(side='left')
no6= Button(bottom_frame, text="6", width= 8)
no6.pack(side='right')
no7= Button(last_frame, text="7", width= 8)
no7.pack(side = 'left')
no8= Button(last_frame, text="8", width= 8)
no8.pack(side='left')
no9= Button(last_frame, text="9", width= 8)
no9.pack(side='right')
plus= Button(final_frame, text= '+', width= 8)
plus.pack(side='left')
minus= Button(final_frame, text= '-', width= 8)
minus.pack(side='left')
times= Button(final_frame, text= 'x', width= 8)
times.pack(side='left')
divide= Button(final_frame2, text= '/', width= 8)
divide.pack(side='left')
equal= Button(final_frame2, text= '=', width= 8)
equal.pack(side='left')
